# Generated by Django 4.2.7 on 2025-05-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
